class ExpensesSpreadsheetException(Exception): ...


class SalariesSpreadsheetException(Exception): ...


class JuniorToSeniorDeltaException(Exception): ...


class PersonalSalaryITDeltaAdjustedException(Exception): ...


class AuthorizationError(Exception): ...


class AvailableFundsException(Exception): ...


class SalaryAnalyticsException(Exception): ...
